/**
 * Static city -> region map, derived from the reference workbook's base data.
 * raw_sales has only `city_name` (no region/state), so the City report's Region
 * column is resolved from this table. Edit/extend as new cities appear.
 */
const CITY_REGION: Record<string, string> = {
  Abohar: "North", Agra: "North", Ahmedabad: "West", Ahmednagar: "West",
  Ajmer: "North", Akola: "West", Aligarh: "North", Alwar: "North",
  Ambala: "North", Ambikapur: "East", Amravati: "West", Amritsar: "North",
  Amroha: "North", Anand: "West", Anantapur: "South", Ankleshwar: "West",
  Arrah: "East", Asansol: "East", Ayodhya: "North", Azamgarh: "North",
  Baddi: "North", Bahadurgarh: "North", Bahraich: "North", Ballari: "South",
  Bangalore: "South", Barabanki: "North", Baraut: "North", Bardhaman: "East",
  Bardoli: "West", Bareilly: "North", Barnala: "North", Basti: "North",
  Batala: "North", Bathinda: "North", Begusarai: "East", Belgaum: "South",
  Berhampur: "East", Bettiah: "East", Bhagalpur: "East", Bharatpur: "North",
  Bharuch: "West", Bhavnagar: "West", Bhilwara: "North", Bhimavaram: "South",
  Bhiwadi: "North", Bhiwani: "North", Bhopal: "North", Bhubaneswar: "East",
  Bhuj: "West", Bidar: "South", "Bihar Sharif": "East", Bijapur: "South",
  Bijnor: "North", Bikaner: "North", Bilaspur: "East", Bokaro: "East",
  Bolpur: "East", Budaun: "North", Buxar: "East", Chandigarh: "North",
  Chandrapur: "West", "Charkhi Dadri": "North",
  "Chatrapati Sambhaji Nagar": "West", Chennai: "South",
  Chikkamagaluru: "South", Chitradurga: "South", Coimbatore: "South",
  Cuttack: "East", Daman: "West", Darbhanga: "East", Davanagere: "South",
  Dehradun: "North", Delhi: "North", Deoghar: "East", Deoria: "North",
  Dewas: "North", Dhanbad: "East", Dharamshala: "North", Dharwad: "South",
  Dibrugarh: "East", Dumka: "East", Durg: "East", Durgapur: "East",
  Eluru: "South", Erode: "South", Etah: "North", Etawah: "North",
  Faridabad: "North", Faridkot: "North", Farrukhabad: "North",
  Fatehpur: "North", Firozabad: "North", Firozpur: "North", Gandhidham: "West",
  Gaya: "East", Ghaziabad: "North", Ghazipur: "North", Giridih: "East",
  Goa: "West", Gonda: "North", Gorakhpur: "North", Gulbarga: "South",
  Guntur: "South", Gurugram: "North", Guwahati: "East", Gwalior: "North",
  Haldwani: "North", Hamirpur: "North", Hansi: "North", Hapur: "North",
  Hardoi: "North", Haridwar: "North", Hassan: "South", Hathras: "North",
  Hazaribagh: "East", Himatnagar: "West", Hisar: "North", Hosapete: "South",
  Hoshiarpur: "North", Hosur: "South", Hubballi: "South", Hyderabad: "South",
  Ichalkaranji: "West", Indore: "North", Itarsi: "Central", Jabalpur: "North",
  Jaipur: "North", Jalandhar: "North", Jalgaon: "West", Jalna: "West",
  Jammu: "North", Jamnagar: "West", Jamshedpur: "East", Jaunpur: "North",
  Jhajjar: "North", Jhansi: "North", Jind: "North", Jodhpur: "North",
  Jorhat: "East", Junagadh: "West", Kaithal: "North", Kakinada: "South",
  Kalol: "West", Kangra: "North", Kanpur: "North", Kapurthala: "North",
  Karad: "West", Karimnagar: "South", Karnal: "North", Kashipur: "North",
  Katihar: "East", Khammam: "South", Khanna: "North", Kharagpur: "East",
  Kharar: "North", Khurja: "North", Kishangarh: "North", Kochi: "South",
  Kolhapur: "West", Kolkata: "East", Kota: "North", Kotdwar: "North",
  Kottayam: "South", Kozhikode: "South", Kurnool: "South",
  Kurukshetra: "North", Lakhimpur: "North", Latur: "West", Lonavala: "West",
  Lucknow: "North", Ludhiana: "North", Madurai: "South", Mahbubnagar: "South",
  Mainpuri: "North", Malda: "East", Manali: "North", Mandya: "South",
  Mangalore: "South", Manipal: "South", Mathura: "North",
  "Maunath Bhanjan (Mau)": "North", Meerut: "North", Mehsana: "West",
  Mirzapur: "North", Modinagar: "North", Moga: "North", Moradabad: "North",
  Morbi: "West", Motihari: "East", Mumbai: "West", Muradnagar: "North",
  Muzaffarnagar: "North", Muzaffarpur: "East", Mysore: "South", Nadiad: "West",
  Nagpur: "West", Nanded: "West", Narmadapuram: "North", Nashik: "West",
  Navsari: "West", Nawada: "East", Nellore: "South", Nizamabad: "South",
  Ongole: "South", Orai: "North", Palanpur: "West", Palwal: "North",
  Panchkula: "North", "Pandit Deen Dayal Upadhyaya Nagar": "East",
  Panipat: "North", Pathankot: "North", Patiala: "North", Patna: "East",
  Perundurai: "South", Phagwara: "North", Pilibhit: "North", Pinjore: "North",
  Prayagraj: "North", Puducherry: "South", Pune: "West", Puri: "East",
  Purnia: "East", Raebareli: "North", Raichur: "South", Raigarh: "Central",
  Raipur: "East", Rajahmundry: "South", Rajkot: "West", Rajpura: "North",
  Ramgarh: "East", Rampur: "North", Ranchi: "East", Ratlam: "North",
  Ratnagiri: "West", Rewa: "North", Rewari: "North", Rishikesh: "North",
  Rohtak: "North", Roorkee: "North", Rudrapur: "North", Rupnagar: "North",
  Sagar: "North", Saharanpur: "North",
  "Sahibzada Ajit Singh Nagar (Mohali)": "North", Salem: "South",
  Samastipur: "East", Sambalpur: "East", Sangareddy: "South", Sangli: "West",
  Sangrur: "North", Satara: "West", Satna: "North", "Sawai Madhopur": "North",
  Shahjahanpur: "North", Shamli: "North", Shikohabad: "North", Shirdi: "West",
  Shivamogga: "South", Sikar: "North", Siliguri: "East", Silvassa: "West",
  Sirsa: "North", Sitapur: "North", Solan: "North", Solapur: "West",
  Sonipat: "North", "Sri Ganganagar": "North", Srikakulam: "South",
  Sultanpur: "North", "Sundar Nagar": "North", Surat: "West",
  Thiruvananthapuram: "South", Thrissur: "South", Tiruchirappalli: "South",
  Tirupati: "South", Tiruppur: "South", Tumkuru: "South", Udaipur: "North",
  Udupi: "South", Ujjain: "North", Una: "North", Unnao: "North",
  Vadodara: "West", Valsad: "West", Vapi: "West", Varanasi: "North",
  Vellore: "South", Vidisha: "Central", Vijayawada: "South",
  Vikasnagar: "North", Visakhapatnam: "South", Vizianagaram: "South",
  Vrindavan: "North", Warangal: "South", Wardha: "West", Yamunanagar: "North",
  Yavatmal: "West", Zirakpur: "North",
};

export function regionForCity(city: string | null | undefined): string {
  if (!city) return "Unknown";
  return CITY_REGION[city] ?? CITY_REGION[city.trim()] ?? "Unknown";
}
